### ISSUE TITLE
Would you mind my sharing your method in Zhihu?

### ISSUE THREAD

**Issue by JiayuanSternLi** [leimao/Frozen_Graph_TensorFlow#2]
Hi, Mao.
Actually, it is not an issue since I have no access to say thanks under your blog post. I was frustrated in freezing graph to pb file with TF2.0 last year, since there was no support, no reply, no article about this problem online. Fortunately, I read your blog and solved the problem of my project yesterday.

I wonder if I could share your method in Chinese in Zhihu with **full references** so that people who had a similar problem could get support. 
Thank you,

**Comment by leimao** [comment]
Hi Jiayuan,
I am very glad to hear that it helped your project. Feel free to share on Zhihu and appreciate your citation. 
PS: Most of the GitHub hosted static websites use [Disqus](https://disqus.com/), you would have to register before making a comment under the blog post. I apologize for the inconvenience.
Best,
Lei

**Comment by leimao** [comment]
Close this since it is not an issue.
