### ISSUE TITLE
"cannot fine the Placeholder op that is an input"

### ISSUE THREAD

**Issue by Coder-nlper** [leimao/Frozen_Graph_TensorFlow#3]
my code:
@tf.function()
def infer(input):
   output=model(input)

gpt2 = infer.get_concrete_function(tf.TensorSpec(shape=(None,None),dtype=tf.int64,name='input'))

''''
error occur here, the error message is the tittle
''''
gpt2_function = convert_variables_to_constants_v2(gpt2)

**Comment by leimao** [comment]
Hi @Coder-nlper ,

I don't have your code to reproduce. In addition, it seems to me that this is a TensorFlow problem instead of a bug in my demo examples.

Best,

Lei

**Comment by Coder-nlper** [comment]
thank you!your demo is ok~it is a tensorflow2.1 bug~
