### ISSUE TITLE
may be you can mention this in "readme.md" about No name 'python' in module 'tensorflow'

### ISSUE THREAD

**Issue by codeoflin** [leimao/Frozen_Graph_TensorFlow#4]
I just copy some code from here ,than I got this problem:
![image](https://user-images.githubusercontent.com/45932283/77025674-b1798f00-69cc-11ea-961f-61294cd74a0a.png)

I spend a few hours to find the solution, than I found this:
https://github.com/Unity-Technologies/ml-agents/issues/1411

they said IT'S NOT A BIG DEAL I can ignore it ,just keep edit the code!
so maybe join this  to your "readme.md" to help readers solve it.

**Comment by leimao** [comment]
Hi @codeoflin ,

Does it only show some messages in your IDE? If there is no problem when you run your program, you can just ignore that. Sometimes the information from IDE is helpful, but sometimes it is not. 

Best,

Lei

**Comment by codeoflin** [comment]
sure, i mean you can join this notice to this file :"readme.md" 
that can make this document more helpful

**Comment by codeoflin** [comment]
![image](https://user-images.githubusercontent.com/45932283/77035645-2d350500-69e8-11ea-8c9c-1f8634702016.png)
 this project is good! it's helped me!
